[client]
showWarningOnDirectExecution = false
gatherUsageStats = false

[logger]
level = "error"

[server]
port = 8000
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200
runOnSave = false

[theme]
primaryColor = "#FF6B35"
backgroundColor = "#1a1a1a"
secondaryBackgroundColor = "#262730"
textColor = "#FFFFFF"
